export const VCT_STAGES = {
  KICKOFF: {
    id: "KICKOFF",
    name: "Kickoff",
    format: "triple_elim" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [4, 3, 2, 1],
    matchWinPts: false,
    qualifiesNext: 3,
    durationWeeks: 6,
    patchId: "1.0",
  },
  MASTERS_1: {
    id: "MASTERS_1",
    name: "Masters",
    format: "swiss_dbl_elim" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [4, 3, 2, 1],
    matchWinPts: false,
    qualifiesNext: 0,
    durationWeeks: 3,
    patchId: "1.1",
    isInternational: true,
    teamsPerRegion: 3,
  },
  STAGE_1: {
    id: "STAGE_1",
    name: "Stage 1",
    format: "round_robin" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [4, 3, 2, 1],
    matchWinPts: true,
    qualifiesNext: 3,
    durationWeeks: 8,
    patchId: "2.0",
    groups: 2,
    teamsPerGroup: 6,
  },
  MASTERS_2: {
    id: "MASTERS_2",
    name: "Masters",
    format: "swiss_dbl_elim" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [4, 3, 2, 1],
    matchWinPts: false,
    qualifiesNext: 0,
    durationWeeks: 3,
    patchId: "2.1",
    isInternational: true,
    teamsPerRegion: 3,
  },
  STAGE_2: {
    id: "STAGE_2",
    name: "Stage 2",
    format: "round_robin" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [4, 3, 2, 1],
    matchWinPts: true,
    qualifiesNext: 2,
    durationWeeks: 10,
    patchId: "3.0",
    groups: 2,
    teamsPerGroup: 6,
  },
  EWC: {
    id: "EWC",
    name: "Esports World Cup",
    format: "double_elim" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [0, 0, 0, 0],
    matchWinPts: false,
    qualifiesNext: 0,
    durationWeeks: 2,
    patchId: "3.0",
    isInternational: true,
    city: "Riyadh",
  },
  CHAMPIONS: {
    id: "CHAMPIONS",
    name: "Champions",
    format: "group_dbl_elim" as const,
    bo: "BO3" as const,
    finalBo: "BO5" as const,
    champPts: [0, 0, 0, 0],
    matchWinPts: false,
    qualifiesNext: 0,
    durationWeeks: 4,
    patchId: "3.1",
    isInternational: true,
    teamsPerRegion: 4,
    groups: 4,
  },
  OFFSEASON: {
    id: "OFFSEASON",
    name: "Off-season",
    format: "offseason" as const,
    bo: null,
    finalBo: null,
    champPts: [0, 0, 0, 0],
    matchWinPts: false,
    qualifiesNext: 0,
    durationWeeks: 8,
    patchId: null,
  },
} as const;

export type StageId = keyof typeof VCT_STAGES;

export const STAGE_ORDER: StageId[] = [
  "KICKOFF",
  "MASTERS_1",
  "STAGE_1",
  "MASTERS_2",
  "STAGE_2",
  "EWC",
  "CHAMPIONS",
  "OFFSEASON",
];

export const CHAMPIONS_SLOTS = { direct: 2, byPoints: 2 } as const;

export const CHAMP_PTS_TIEBREAK_ORDER: StageId[] = [
  "STAGE_2",
  "MASTERS_2",
  "STAGE_1",
  "MASTERS_1",
  "KICKOFF",
];

export const HOST_CITIES = [
  "Paris", "Tokyo", "Berlin", "São Paulo", "Istanbul",
  "Seoul", "Los Angeles", "Sydney", "Copenhagen", "Dubai",
  "Bangkok", "Mexico City", "Toronto", "Cape Town", "Madrid",
  "Singapore", "Busan", "Mumbai", "Stockholm", "Reykjavik",
] as const;
